version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Xvfb (Cypress dependency)
          command: sudo apt-get update && sudo apt-get install -y xvfb
      - run:
          name: Run tests
          command: npx cypress open
  cypress-test:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
            - node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Run Cypress tests
          command: npx cypress run
      - store_artifacts:
          path: cypress/videos
          destination: cypress-videos
      - store_artifacts:
          path: cypress/screenshots
          destination: cypress-screenshots
  cypress-run:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run npx cypress run
          command: npx cypress run
workflows:
  build-and-test:
    jobs:
      - test-node
      - cypress-test:
          requires:
            - test-node
      - cypress-run:
          requires:
            - test-node
